# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-12-21 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mywebsite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='\u7f51\u7ad9')),
                ('desc', models.URLField(blank=True, null=True, verbose_name='\u63cf\u8ff0')),
            ],
        ),
    ]
