# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-12-21 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mywebsite',
            options={'verbose_name': '\u7f51\u7ad9', 'verbose_name_plural': '\u6211\u7684\u7f51\u7ad9'},
        ),
        migrations.RemoveField(
            model_name='mywebsite',
            name='title',
        ),
        migrations.AddField(
            model_name='mywebsite',
            name='sitename',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='sitename'),
        ),
        migrations.AlterField(
            model_name='mywebsite',
            name='desc',
            field=models.URLField(blank=True, null=True, verbose_name='desc'),
        ),
    ]
