# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-12-21 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybook', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='books',
            options={'verbose_name': '\u4e66\u5355', 'verbose_name_plural': '\u6211\u7684\u4e66\u5355'},
        ),
        migrations.AlterField(
            model_name='books',
            name='bookendtime',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='bookendtime'),
        ),
        migrations.AlterField(
            model_name='books',
            name='bookinfo',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='bookinfo'),
        ),
        migrations.AlterField(
            model_name='books',
            name='bookremark',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='bookremark'),
        ),
        migrations.AlterField(
            model_name='books',
            name='bookstarttime',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='bookstarttime'),
        ),
        migrations.AlterField(
            model_name='books',
            name='booktype',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='booktype'),
        ),
    ]
